---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: fetch
    image: alpine/git
    commands:
    #- git submodule update --init --recursive
    - git fetch --tags

  - name: test
    image: golang:1.20.1
    commands:
    - go test -v ./...
    - go build ./...
    depends_on: [ clone ]

  - name: release
    image: golang:1.20.1
    environment:
      FURY_TOKEN:
        from_secret: fury_token
    commands:
    - curl -sL https://git.io/goreleaser | bash -s -- --skip-publish
    - ./scripts/fury-publish
    when:
      event: tag
    depends_on: [ test ]
---
kind: signature
hmac: e144dcb26466edc9f64f090128d3c2a502aba5fdcdfc132220afe02c516efcbe

...
