---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: fetch
    image: alpine/git
    commands:
    #- git submodule update --init --recursive
    - git fetch --tags

  - name: test
    image: golang:1.19.5
    commands:
    - go test -v ./...
    - go build ./...
    depends_on: [ clone ]

  - name: release
    image: golang:1.19.5
    environment:
      FURY_TOKEN:
        from_secret: fury_token
    commands:
    - curl -sL https://git.io/goreleaser | bash -s -- --skip-publish
    - ./scripts/fury-publish
    when:
      event: tag
    depends_on: [ test ]
---
kind: signature
hmac: 4f26c1b5d33078a34ec37129b8c18e1d7b4dafc1150760f51c12de9c8bae513d

...
